# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_pobs <- function(x) {
    .Call(`_RoDiCE_rcpp_pobs`, x)
}

rcpp_cvm <- function(mat1, mat2) {
    .Call(`_RoDiCE_rcpp_cvm`, mat1, mat2)
}

rcpp_coptest <- function(mat1, mat2, nperm) {
    .Call(`_RoDiCE_rcpp_coptest`, mat1, mat2, nperm)
}

